from tei_transform.observer.byline_sibling_observer import BylineSiblingObserver
from tei_transform.observer.classcode_observer import ClasscodeObserver
from tei_transform.observer.div_text_observer import DivTextObserver
from tei_transform.observer.double_cell_observer import DoubleCellObserver
from tei_transform.observer.double_item_observer import DoubleItemObserver
from tei_transform.observer.filename_element_observer import FilenameElementObserver
from tei_transform.observer.head_after_p_element_observer import (
    HeadAfterPElementObserver,
)
from tei_transform.observer.head_with_type_attr_observer import HeadWithTypeAttrObserver
from tei_transform.observer.hi_with_wrong_parent_observer import (
    HiWithWrongParentObserver,
)
from tei_transform.observer.id_attribute_observer import IdAttributeObserver
from tei_transform.observer.list_as_div_sibling_observer import ListAsDivSiblingObserver
from tei_transform.observer.missing_publisher_observer import MissingPublisherObserver
from tei_transform.observer.notesstmt_observer import NotesStmtObserver
from tei_transform.observer.p_as_div_sibling_observer import PAsDivSiblingObserver
from tei_transform.observer.schemalocation_observer import SchemaLocationObserver
from tei_transform.observer.tail_text_observer import TailTextObserver
from tei_transform.observer.tei_namespace_observer import TeiNamespaceObserver
from tei_transform.observer.teiheader_observer import TeiHeaderObserver
from tei_transform.observer.textclass_observer import TextclassObserver
