from tei_transform.observer.author_type_observer import AuthorTypeObserver
from tei_transform.observer.byline_sibling_observer import BylineSiblingObserver
from tei_transform.observer.classcode_observer import ClasscodeObserver
from tei_transform.observer.code_element_observer import CodeElementObserver
from tei_transform.observer.div_parent_observer import DivParentObserver
from tei_transform.observer.div_sibling_observer import DivSiblingObserver
from tei_transform.observer.div_tail_observer import DivTailObserver
from tei_transform.observer.div_text_observer import DivTextObserver
from tei_transform.observer.double_cell_observer import DoubleCellObserver
from tei_transform.observer.double_item_observer import DoubleItemObserver
from tei_transform.observer.double_plike_observer import DoublePlikeObserver
from tei_transform.observer.empty_element_observer import EmptyElementObserver
from tei_transform.observer.filename_element_observer import FilenameElementObserver
from tei_transform.observer.head_after_p_element_observer import (
    HeadAfterPElementObserver,
)
from tei_transform.observer.head_with_type_attr_observer import HeadWithTypeAttrObserver
from tei_transform.observer.hi_with_wrong_parent_observer import (
    HiWithWrongParentObserver,
)
from tei_transform.observer.id_attribute_observer import IdAttributeObserver
from tei_transform.observer.linebreak_div_observer import LinebreakDivObserver
from tei_transform.observer.list_text_observer import ListTextObserver
from tei_transform.observer.lonely_cell_observer import LonelyCellObserver
from tei_transform.observer.lonely_item_observer import LonelyItemObserver
from tei_transform.observer.lonely_row_observer import LonelyRowObserver
from tei_transform.observer.missing_publisher_observer import MissingPublisherObserver
from tei_transform.observer.notesstmt_observer import NotesStmtObserver
from tei_transform.observer.p_as_div_sibling_observer import PAsDivSiblingObserver
from tei_transform.observer.related_item_observer import RelatedItemObserver
from tei_transform.observer.schemalocation_observer import SchemaLocationObserver
from tei_transform.observer.table_text_observer import TableTextObserver
from tei_transform.observer.tail_text_observer import TailTextObserver
from tei_transform.observer.tei_namespace_observer import TeiNamespaceObserver
from tei_transform.observer.teiheader_type_observer import TeiHeaderTypeObserver
from tei_transform.observer.textclass_observer import TextclassObserver
